CREATE DATABASE database02
USE database02

CREATE TABLE District (
districtName VARCHAR(10) NOT NULL,
districtId INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE Street (
streetName VARCHAR(30) NOT NULL,
streetNumber INT,
streetId INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE City (
cityName VARCHAR(10) NOT NULL,
cityId INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE Country (
countryName VARCHAR(10) NOT NULL UNIQUE,
countryId INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE Clients (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(20) UNIQUE,
nameClient VARCHAR(20) NOT NULL,
cpf INT NOT NULL UNIQUE,
phone INT,
sex CHAR(1) NOT NULL,
streetId INT,
districtId INT,
cityId INT,
countryId INT
)

ALTER TABLE Clients ADD FOREIGN KEY(streetId) REFERENCES Street (streetId);
ALTER TABLE Clients ADD FOREIGN KEY(districtId) REFERENCES District (districtId);
ALTER TABLE Clients ADD FOREIGN KEY(cityId) REFERENCES City (cityId);
ALTER TABLE Clients ADD FOREIGN KEY(countryId) REFERENCES Country (countryId);

ALTER TABLE Clients MODIFY COLUMN streetId INT AUTO_INCREMENT;
ALTER TABLE Clients MODIFY COLUMN districtId INT AUTO_INCREMENT;
ALTER TABLE Clients MODIFY COLUMN cityId INT AUTO_INCREMENT;
ALTER TABLE Clients MODIFY COLUMN countryId INT AUTO_INCREMENT;

DESC Clients

