INSERT INTO Courses VALUES (NULL, 'Database fundaments', 25, 200.00);

SELECT * FROM Courses

-- procedure
DELIMITER $
CREATE PROCEDURE cad_cursos (P_NOME VARCHAR(30), P_HORAS INT(3), P_PRECO FLOAT(10, 2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
$

DELIMITER ;
CALL CAD_CURSOS('BI SQL SERVER, 35, 200.00');