CREATE DATABASE teste3;
USE teste3;

CREATE TABLE TPEOPLE (
CPERSON_ID INT PRIMARY KEY AUTO_INCREMENT,
CCODE INT(9) NOT NULL,
CFULL_NAME VARCHAR(30) NOT NULL,
CDOCUMENT INT(5) NOT NULL,
CBORN_DATE DATE NOT NULL,
AGE INT (3)
);

INSERT INTO TPEOPLE (CCODE, CFULL_NAME, CDOCUMENT, CBORN_DATE, AGE)
VALUES(123, 'Sabrina', '5118', '1994-01-26', TIMESTAMPDIFF(YEAR, CBORN_DATE, NOW())), 
			(456, 'Alexander', '8115', '1993-10-04', TIMESTAMPDIFF(YEAR, CBORN_DATE, NOW())),
			(915, 'Rodrigo', '1158', '1987-10-12', TIMESTAMPDIFF(YEAR, CBORN_DATE, NOW())),
			(789, 'Rodrigo', '1159', '1969-02-05', TIMESTAMPDIFF(YEAR, CBORN_DATE, NOW())),
			(101112, 'Roger', '5181', '1999-07-08', TIMESTAMPDIFF(YEAR, CBORN_DATE, NOW()));

-- query 1
SELECT CCODE, CFULL_NAME, CDOCUMENT, CBORN_DATE 
    FROM TPEOPLE 
    WHERE CFULL_NAME LIKE 'Rodr%' 
    ORDER BY CDOCUMENT;

-- query 2
SELECT CCODE, CFULL_NAME, CDOCUMENT, CBORN_DATE, AGE
FROM
    TPEOPLE
WHERE AGE > '20'
ORDER BY AGE;